
use('test');
db.getCollection("group_demo").insertMany([
    {
        type:1,
        status:2,
    },
    {
        type:1,
        status:2,
    },
    {
        type:1,
        status:3,
    },
    {
        type:2,
        status:1,
    },
    {
        type:2,
        status:1,
    },
]);
db.getCollection("group_demo").find({})
use('test');
db.getCollection("group_demo").aggregate([
    {
        "$group":{
            _id:{"type":"$type",status:"$status"},
            count:{"$sum":1},
        }
    },
    {
        $set: {
          _id:0,
          type:"$_id.type",
          status:"$_id.status",
          count:"$count",
        }
    }
])